name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  actions: read
  pull-requests: write
  issues: read
  checks: write

env:
  VERSION: ${{ github.event.pull_request.number }}-${{ github.run_number }}
  JAVA_HOME: '' # force JAVA_HOME to be empty, so gradle will use the sdkman java version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache SDKMAN
        uses: actions/cache@v4
        with:
          path: ~/.sdkman
          key: sdkman-${{ runner.os }}-${{ hashFiles('.sdkmanrc') }}

      - name: Install SDKMAN
        uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml

      - uses: jwgmeligmeyling/checkstyle-github-action@v1
        with:
          path: 'build/reports/checkstyle/main.xml'

      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test report
          path: build/reports/tests

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - name: Code vulnerability scan
        uses: anchore/scan-action@v6
        with:
          path: '${{ github.workspace }}/build/libs'
          fail-build: true
          severity-cutoff: 'high'
          output-format: table
          only-fixed: false
