name: Enforce Reviewers on Main Branch

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  enforce-reviewers-main:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Remove all non-release-engineers reviewers
        run: |
          echo "Fetching current reviewers..."
          reviewers=$(gh pr view "$PR_URL" --json reviewRequests -q '.reviewRequests[].requestedReviewer.login')
          removed_any=false

          for reviewer in $reviewers; do
            if [[ "$reviewer" != "maze-technology/release-engineers" ]]; then
              echo "Removing reviewer: $reviewer"
              gh pr edit "$PR_URL" --remove-reviewer "$reviewer"
              removed_any=true
            fi
          done

          echo "Removed reviewers: $removed_any"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add release-engineers team as reviewer
        run: |
          echo "Adding maze-technology/release-engineers as reviewer"
          gh pr edit "$PR_URL" --add-reviewer maze-technology/release-engineers
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post comment to explain reviewer enforcement
        run: |
          gh pr comment "$PR_URL" --body "👋 Heads-up: This PR targets \`main\`. The workflow automatically enforced reviewers by assigning **@maze-technology/release-engineers** and removing others to follow the release policy."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
