name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

env:
  VERSION: security-scan-${{ github.run_number }}
  JAVA_HOME: '' # force JAVA_HOME to be empty, so gradle will use the sdkman java version

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USERNAME: x-access-token
    outputs:
      APP_NAME: ${{ steps.app_name.outputs.value }}
    steps:
      - id: app_name
        run: echo "value=$(echo '${{ github.repository }}' | awk -F '.' '{print $3}')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Cache SDKMAN
        uses: actions/cache@v4
        with:
          path: ~/.sdkman
          key: sdkman-${{ runner.os }}-${{ hashFiles('.sdkmanrc') }}

      - name: Install SDKMAN
        uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Code vulnerability scan
        uses: anchore/scan-action@v6
        with:
          path: '${{ github.workspace }}/build/libs'
          fail-build: true
          severity-cutoff: 'high'
          output-format: table
          only-fixed: false
